tiles.setCurrentTilemap(tilemap`level`)
let _package = sprites.create(assets.image`myImage4`, SpriteKind.Player)
_package.setPosition(53, 79)
let dede = sprites.create(assets.image`myImage2`, SpriteKind.Player)
dede.setPosition(55, 52)
let drByte = sprites.create(assets.image`myImage5`, SpriteKind.Player)
drByte.setPosition(32, 75)
let bug = sprites.create(assets.image`goomba1`, SpriteKind.Player)
bug.setPosition(85, 75)
let zappy = sprites.create(assets.image`myImage`, SpriteKind.Player)
zappy.setPosition(125, 75)
